---
name: Test

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  test-clj:
    strategy:
      matrix:
        clojure: ["1.10.3.1058"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: ${{ matrix.clojure }}
      - name: Setup cljstyle
        run: |
          curl -sLO https://raw.githubusercontent.com/greglook/cljstyle/main/script/install-cljstyle
          chmod +x install-cljstyle
          sudo ./install-cljstyle
      - name: Setup clj-kondo
        run: |
          curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          sudo ./install-clj-kondo
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-clj-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-
      - name: Test
        run: |
          make test-clj test-cljs

  test-clje:
    strategy:
      matrix:
        erlang: ["24.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            _build
          key: ${{ runner.os }}-erl${{ matrix.erlang }}-${{ hashFiles('rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-erl${{ matrix.erlang }}-
      - name: Test
        run: |
          make test-clje

  test-cljr:
    strategy:
      matrix:
        clojure-clr: ["1.10.0"]
        dotnet: ["5.x"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Setup Clojure CLR
        run: |
          dotnet tool install --global --version ${{ matrix.clojure-clr }} Clojure.Main
      - uses: actions/checkout@v2
      - name: Test
        run: |
          Clojure.Main .\dev\task\test_cljr.clj
