---
name: Test

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  test-clj:
    strategy:
      matrix:
        clojure: ["1.10.2.774"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          cli: ${{ matrix.clojure }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-clj-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-
      - name: Lint & test
        run: |
          make test-clj test-cljs

  test-clje:
    strategy:
      matrix:
        elixir: ["1.11.x"]
        erlang: ["23.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            _build
          key: ${{ runner.os }}-erl${{ matrix.erlang }}-${{ hashFiles('rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-erl${{ matrix.erlang }}-
      - name: Lint & test
        run: |
          make test-clje

  test-cljr:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Lint & test
        run: |
          Register-PackageSource -Name NuGet -Location https://api.nuget.org/v3/index.json -ProviderName NuGet

          Install-Package Clojure -Force -ProviderName NuGet
          cp 'C:\Program Files\PackageManagement\NuGet\Packages\Clojure.1.9.0\lib\net40\*' 'C:\Program Files\PackageManagement\NuGet\Packages\Clojure.1.9.0\tools\net40'
          $env:Path = $env:Path + ';C:\Program Files\PackageManagement\NuGet\Packages\Clojure.1.9.0\tools\net40'

          Install-Package clojure.spec.alpha -Force
          cp 'C:\Program Files\PackageManagement\NuGet\Packages\clojure.spec.alpha.*\lib\netstandard2.1\*' .

          Install-Package clojure.core.specs.alpha -Force
          cp 'C:\Program Files\PackageManagement\NuGet\Packages\clojure.core.specs.alpha.*\lib\netstandard2.1\*' .

          Clojure.Main .\dev\task\test_cljr.clj
